name: ci

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited
    # - closed
    branches:
    - main
  workflow_dispatch:

jobs:
  build-ion-services:
    name: build ion-${{ matrix.svc }} (${{ matrix.dotnet-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        svc:
        - job
        - microservice
        os: 
        - ubuntu-latest
        - windows-latest
        - macos-latest
        dotnet-version:
        - '5.0.400'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: nuget.config (pwsh)
      shell: pwsh
      run: |
        $nuget = @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            <add key="nuget.cloudtek.io" value="${{ secrets.NUGET_FEED_CLOUDTEK }}" protocolVersion="3"/>
            <add key="nuget.ionizd.io" value="${{ secrets.NUGET_FEED_IONIZD }}" protocolVersion="3"/>
          </packageSources>
          <packageRestore>
            <add key="enabled" value="True" />
            <add key="automatic" value="True" />
          </packageRestore>
          <bindingRedirects>
            <add key="skip" value="False" />
          </bindingRedirects>
          <packageManagement>
            <add key="format" value="0" />
            <add key="disabled" value="False" />
          </packageManagement>
          <packageSourceCredentials>
            <nuget.cloudtek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloudtek.io>
            <nuget.ionizd.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.ionizd.io>
          </packageSourceCredentials>
        </configuration>
        "@

        $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config

    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: dotnet restore
      run: |
        dotnet restore ProjectName.sln
      shell: bash
      working-directory: ${{ matrix.svc }}
    - name: dotnet build
      run: |
        dotnet build ProjectName.sln
      shell: bash
      working-directory: ${{ matrix.svc }}

  render-templates:
    name: render ${{ matrix.svc }} ${{ matrix.dotnet-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
    - build-ion-services
    strategy:
      matrix: 
        svc:
        - job
        - microservice
        os: 
        - ubuntu-latest
        - windows-latest
        - macos-latest
        dotnet-version:
        - '5.0.400'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: nuget.config (pwsh)
      shell: pwsh
      run: |
        $nuget = @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            <add key="nuget.cloudtek.io" value="${{ secrets.NUGET_FEED_CLOUDTEK }}" protocolVersion="3"/>
            <add key="nuget.ionizd.io" value="${{ secrets.NUGET_FEED_IONIZD }}" protocolVersion="3"/>
          </packageSources>
          <packageRestore>
            <add key="enabled" value="True" />
            <add key="automatic" value="True" />
          </packageRestore>
          <bindingRedirects>
            <add key="skip" value="False" />
          </bindingRedirects>
          <packageManagement>
            <add key="format" value="0" />
            <add key="disabled" value="False" />
          </packageManagement>
          <packageSourceCredentials>
            <nuget.cloudtek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloudtek.io>
            <nuget.ionizd.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.ionizd.io>
          </packageSourceCredentials>
        </configuration>
        "@

        $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config
    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - uses: actions/setup-dotnet@v1
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |
        Install-Module Pester -Force;
        Invoke-Pester ${{ github.workspace }}/Tests.ps1 -Tag ${{ matrix.svc }} -Passthru;