name: ci

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited
    # - closed
    branches:
    - main
  workflow_dispatch:

jobs:
  pre-build-templates:
    name: ${{ matrix.svc }} ${{ matrix.dotnet-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        svc:
        - job
        - microservice
        - microservice-api
        - microservice-minimal-api
        - microservice-graphql-api
        - microservice-grpc-api
        - microservice-grpc-minimal-api
        os:
        - ubuntu-latest
        # - windows-latest
        - macos-latest
        dotnet-version:
        - '7.0.101'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: nuget.config (pwsh)
      shell: pwsh
      run: |
        $nuget = @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            <add key="nuget.cloudtek.io" value="${{ secrets.NUGET_FEED_CLOUDTEK }}" protocolVersion="3"/>
            <add key="nuget.cloud-tek.io" value="${{ secrets.NUGET_FEED_IONIZD }}" protocolVersion="3"/>
          </packageSources>
          <packageRestore>
            <add key="enabled" value="True" />
            <add key="automatic" value="True" />
          </packageRestore>
          <bindingRedirects>
            <add key="skip" value="False" />
          </bindingRedirects>
          <packageManagement>
            <add key="format" value="0" />
            <add key="disabled" value="False" />
          </packageManagement>
          <packageSourceCredentials>
            <nuget.cloudtek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloudtek.io>
            <nuget.cloud-tek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloud-tek.io>
          </packageSourceCredentials>
        </configuration>
        "@

        $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config

    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - uses: actions/setup-dotnet@v3
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: dotnet restore
      run: |
        dotnet restore ProjectName.ServiceName.sln
      shell: bash
      working-directory: ${{ matrix.svc }}
    - name: dotnet build
      run: |
        dotnet build ProjectName.ServiceName.sln
      shell: bash
      working-directory: ${{ matrix.svc }}

  render-templates:
    name: ${{ matrix.dotnet-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
    - pre-build-templates
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        - macos-latest
        dotnet-version:
        - '7.0.101'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: nuget.config (pwsh)
      shell: pwsh
      run: |
        $nuget = @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            <add key="nuget.cloudtek.io" value="${{ secrets.NUGET_FEED_CLOUDTEK }}" protocolVersion="3"/>
            <add key="nuget.cloud-tek.io" value="${{ secrets.NUGET_FEED_IONIZD }}" protocolVersion="3"/>
          </packageSources>
          <packageRestore>
            <add key="enabled" value="True" />
            <add key="automatic" value="True" />
          </packageRestore>
          <bindingRedirects>
            <add key="skip" value="False" />
          </bindingRedirects>
          <packageManagement>
            <add key="format" value="0" />
            <add key="disabled" value="False" />
          </packageManagement>
          <packageSourceCredentials>
            <nuget.cloudtek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloudtek.io>
            <nuget.cloud-tek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloud-tek.io>
          </packageSourceCredentials>
        </configuration>
        "@

        $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config
    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - uses: actions/setup-dotnet@v3
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |
        Install-Module Pester -Force;
        $p = Invoke-Pester ${{ github.workspace }}/Tests.ps1 `
          -Tag "template-rendering" `
          -OutputFile ${{ github.workspace }}/TestResults.xml `
          -OutputFormat JUnitXml `
          -Passthru;
        $p | Export-JUnitReport -Path ${{ github.workspace }}/TestResults.xml
        if ($p.FailedCount -gt 0) {
          exit 1;
        }
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: ${{ github.workspace }}/TestResults.*.xml

  post-build-templates:
    name: ${{ matrix.dotnet-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
    - render-templates
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        - macos-latest
        dotnet-version:
        - '7.0.101'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: nuget.config (pwsh)
      shell: pwsh
      run: |
        $nuget = @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            <add key="nuget.cloudtek.io" value="${{ secrets.NUGET_FEED_CLOUDTEK }}" protocolVersion="3"/>
            <add key="nuget.cloud-tek.io" value="${{ secrets.NUGET_FEED_IONIZD }}" protocolVersion="3"/>
          </packageSources>
          <packageRestore>
            <add key="enabled" value="True" />
            <add key="automatic" value="True" />
          </packageRestore>
          <bindingRedirects>
            <add key="skip" value="False" />
          </bindingRedirects>
          <packageManagement>
            <add key="format" value="0" />
            <add key="disabled" value="False" />
          </packageManagement>
          <packageSourceCredentials>
            <nuget.cloudtek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloudtek.io>
            <nuget.cloud-tek.io>
              <add key="Username" value="${{ secrets.NUGET_USERNAME }}"/>
              <add key="ClearTextPassword" value="${{ secrets.NUGET_PASSWORD }}" />
            </nuget.cloud-tek.io>
          </packageSourceCredentials>
        </configuration>
        "@

        $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config
    - name: dotnet tool restore
      run: dotnet tool restore
      shell: bash
    - uses: actions/setup-dotnet@v3
      name: dotnet installer
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |
        Install-Module Pester -Force;
        $p = Invoke-Pester ${{ github.workspace }}/Tests.ps1 `
          -Tag "template-build" `
          -OutputFile ${{ github.workspace }}/TestResults.xml `
          -OutputFormat JUnitXml `
          -Passthru;
        $p | Export-JUnitReport -Path ${{ github.workspace }}/TestResults.xml
        if ($p.FailedCount -gt 0) {
          exit 1;
        }
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: ${{ github.workspace }}/TestResults.*.xml
